### ISSUE TITLE
[1.16.5] Client crash in multiplayer

### ISSUE THREAD

**Issue by TheSnowyChickens** [Samarium150/StructuresCompass#12]
Hello,

I wanted to open the GUI from your compass in multiplayer, but it crashes the client everytime.

[crash-2021-08-16_03.47.52-client.txt](https://github.com/Samarium150/StructuresCompass/files/6989313/crash-2021-08-16_03.47.52-client.txt)

MC: 1.16.5
SC: 1.2.0
Forge: 36.2.2

**Comment by Samarium150** [comment]
Does it work in single-player mode?

**Comment by TheSnowyChickens** [comment]
Yes

**Comment by Samarium150** [comment]
Would you like to pack your mods and share them with us directly?

**Comment by TheSnowyChickens** [comment]
[KRK - Endless - 1.16.5 - 0.0.1.zip](https://github.com/Samarium150/StructuresCompass/files/6989755/KRK.-.Endless.-.1.16.5.-.0.0.1.zip)

Serverpack with some more YUNGs better* mods and all the non client mods from the client. (server on linux)

**Comment by Samarium150** [comment]
<img src='https://user-images.githubusercontent.com/28302241/129536485-db24b4a0-c7a9-4754-8a42-357349ceaa16.png'  style='width: 50%'/>

![image](https://user-images.githubusercontent.com/28302241/129536981-a2467d28-4f31-454d-87ef-220c9f82f02f.png)

I used the mods you provided, and it seems ok? But I run the server on Windows.

**Comment by TheSnowyChickens** [comment]
hmmm weird, with normal right click I get the message in the chat, but with shift-right it instantly crashes.

Maybe windows can help there, but on windows the server lag is by far higher in our case (13ms lag linux, 20ms lag windows)

**Comment by Samarium150** [comment]
Ok, I set up a temporary Linux server at 140.82.60.187:25565, and I had no issue with the GUI. You could connect the server and test it out.

**Comment by TheSnowyChickens** [comment]
Hi,
please let me test this today after noon, we started the server today with the players and had so many performance problems (20ms in an empty world) that i already got a headache from it.

(I am online in 10 hours)

**Comment by Samarium150** [comment]
No problem, I can let the server open for a while. Feel free to find a suitable time for you.

**Comment by TheSnowyChickens** [comment]
Okay. I am online and yes, no crash.

Let me try it with the blur mod installed, because the blur mod can crash the client, while opening the inventory. (for some players)

**Comment by TheSnowyChickens** [comment]
Update: okay, it is not blur.

Now I am confused.

**Comment by Samarium150** [comment]
Could you please give me a zip of client mods? I think some of them cause the crash.

**Comment by TheSnowyChickens** [comment]
Somehow I fixed Curse, new link:

https://cloud.krk-gaming.de/s/QJ6yNZkeDnNHdMb

**Comment by Samarium150** [comment]
<img src="https://user-images.githubusercontent.com/28302241/130167684-cf4ccb07-7f8f-4359-b00f-c72d40895422.png" style="width: 50%"/>

<img src="https://user-images.githubusercontent.com/28302241/130167690-f342a452-8933-4656-bd9d-77545d375be6.png" style="width: 30%"/>

I tested again on both Windows and Linux with the mods, and the GUI still works.

**Comment by TheSnowyChickens** [comment]
Now I don't understand the world. xD

It is maybe something with my PC or so ?
You see the crash log, tell me what I can do. :(

**Comment by Samarium150** [comment]
So I discussed with my friend, the co-author @SnightW. We think if your client works fine on single-player and multiplayer on my server, it might be something wrong with your server.

**Comment by Samarium150** [comment]
From the crash log, I saw there are 4 players in total in your server. How about others' situations? Did they encounter the crash as well?

**Comment by TheSnowyChickens** [comment]
I hotfix disabled the compass on the server, because the crash on my side.

I can enable him again and give you feedback then.

**Comment by TheSnowyChickens** [comment]
Result: it is crashing for everyone for us.

[crash-2021-08-23_16.50.07-client.txt](https://github.com/Samarium150/StructuresCompass/files/7032836/crash-2021-08-23_16.50.07-client.txt)

**Comment by Samarium150** [comment]
As expected 😞 
My server is still open, please let your freinds have a try, and here is my packed [server files](https://drive.google.com/file/d/1vFvx79Hk8Tl3bq3I1iY2pBL_vr7g1Zpq/view?usp=sharing).

**Comment by TheSnowyChickens** [comment]
![grafik](https://user-images.githubusercontent.com/29357962/130673569-0d964a8d-3fd0-4787-b4d9-b64566a5617b.png)

Interesting, it work. xD
Maybe it has to do with the incredible bad performance. (20ms in a empty world)'
We re-created the modpack with 90% of the same old mods and configs and the performance is by far better (2ms in a empty world) and maybe it won't crash anymore. 
Hmmm

**Comment by Samarium150** [comment]
Sorry, I was too busy to reply. I'll close the issue for now, and if you need any further assistance, just let me know.

**Comment by TheSnowyChickens** [comment]
Okay, a little update to this crash:

we exchanged the structure compass mod with the one from the natures compass dev and this compass also let the player crash in multiplayer.

I have a strong suspicion that it is due to the Yungs mods, becasue Yungs mods change something with /locate stronghold and:
A: we need to have the mods also on the client installed to work and not crash
or
B: Yungs mods just destroy any /locate using mod.

**Comment by Samarium150** [comment]
> Okay, a little update to this crash:
> 
> we exchanged the structure compass mod with the one from the natures compass dev and this compass also let the player crash in multiplayer.
> 
> I have a strong suspicion that it is due to the Yungs mods, because Yungs mods change something with /locate stronghold and:
> A: we need to have the mods also on the client installed to work and not crash
> or
> B: Yungs mods just destroy any /locate using mod.

You mean you tried `Explore's Compass` and also crashed.

**Comment by TheSnowyChickens** [comment]
Yes
