### ISSUE TITLE
feat: display HUD when the compass is in offhand

### ISSUE THREAD

**Issue by WenXin20** [Samarium150/StructuresCompass#14]
`Minecraft v1.18.1`
`Forge v39.0.79`

When the Structure's Compass is held in the offhand, the gui coordinates and other info does not display on screen.

**Comment by Samarium150** [comment]
> When the Structure's Compass is held in the offhand, the gui coordinates and other info does not display on screen.

We actually didn't design the HUD display on the offhand. This will be a new feature, and we will implement it soon.

**Comment by WenXin20** [comment]
Thanks, sounds good!
