### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by MrHamid-am** [Samarium150/StructuresCompass#15]
HELLO
me and my friends love this mod, but when we try to use it on server-side, we get this exception and game crashes.

[crash-2022-02-25_23.07.42-client.txt](https://github.com/Samarium150/StructuresCompass/files/8146818/crash-2022-02-25_23.07.42-client.txt)

minecraft: 1.18.1-forge
Forge version: 39.0.79

**Comment by MrHamid-am** [comment]
yes sure, this is my mod pack on both sides:
https://drive.google.com/file/d/1qwpEvP5tYgMIwE3NYtUDxu_43EFInLZS/view?usp=sharing
when we try to use the compass on server, game crashes, we don't have any problem in single player

**Comment by MrHamid-am** [comment]
> would you like to share your server modpack, so that I could test it out? By the way, is this exception thrown in single-player?

sorry if I take too long to answer

**Comment by Samarium150** [comment]
Somehow, I'm not able to reproduce the exception.
![image](https://user-images.githubusercontent.com/28302241/155867423-e30db716-850e-4b44-b050-254a638805ba.png)

**Comment by MrHamid-am** [comment]
> Somehow, I'm not able to reproduce the exception. ![image](https://user-images.githubusercontent.com/28302241/155867423-e30db716-850e-4b44-b050-254a638805ba.png)

I figured it out, it because of my world.

**Comment by Samarium150** [comment]
> I figured it out, it because of my world.

Sounds good!

**Comment by GnomTocha** [comment]
Faced a similar problem. Through trial and error, I found out that the crash is most likely due to the lack of mods for generating structures from the client side. Since most of these modifications are enough to put only on the server side.

**Comment by MrHamid-am** [comment]
> Faced a similar problem. Through trial and error, I found out that the crash is most likely due to the lack of mods for generating structures from the client side. Since most of these modifications are enough to put only on the server side. This is my personal guess. Version 1.16.5

That's exactly the case
