### ISSUE TITLE
End City dimension location is in Overworld instead of The End

### ISSUE THREAD

**Issue by mrjqr** [Samarium150/StructuresCompass#19]
Minecraft version 1.18.2
Fabric API 0.50.0
Structures Compass v1.4.1

when looking for end cities it says its dimension is in the overworld and when I'm in the end it says wrong dimension

![Screenshot 2022-04-12 135849](https://user-images.githubusercontent.com/103484349/162894680-b8a6c010-1bba-4288-aa93-d6f02a4286fb.jpg)

**Comment by Samarium150** [comment]
Notes for dev:
- Fabric Version:
```kotlin
println(Registry.STRUCTURE_FEATURE.entrySet)
println(serverWorld.registryManager.get(Registry.CONFIGURED_STRUCTURE_FEATURE_KEY).entrySet)
```
- Forge Version:
```java
System.out.println(ForgeRegistries.STRUCTURE_FEATURES.getEntries());
System.out.println(serverWorld.registryAccess()
    .registryOrThrow(Registry.CONFIGURED_STRUCTURE_FEATURE_REGISTRY).entrySet());
```
Output:
```
$> ResourceKey[minecraft:worldgen/structure_feature / minecraft:endcity]
$> ResourceKey[minecraft:worldgen/configured_structure_feature / minecraft:end_city]
```

**Comment by Samarium150** [comment]
@mrjqr A new version has been released on CurseForge, please check it out.

**Comment by mrjqr** [comment]
It's working now, thank you so much for fixing it!
