### ISSUE TITLE
Can't locate YUNG's Better Mineshaft

### ISSUE THREAD

**Issue by jlaine3333** [Samarium150/StructuresCompass#22]
**Describe the bug**
Gets stuck on "Searching..." only for YUNG's Better Mineshaft structures. Waiting any length of time changes nothing.

**To Reproduce**
1. Install this mod and YUNG's Better Mineshafts
2. Search for structure.bettermineshafts.mineshaft
3. Wait

**Expected behavior**
It should locate the mineshaft as quickly as any other structure.

**Versions:**
 - Minecraft: 1.18.2
 - Mod Loader: Forge 40.1.60
 - Mod Version: 1.4.1

**Comment by jlaine3333** [comment]
I forgot to mention: Explorer's Compass and /locate do find the structure without issue.

**Comment by Samarium150** [comment]
Would you like to provide logs when you searching?
